#pragma once

#define PHASE_PWM_MIN 48000
#define PHASE_PWM_MAX 128000

#define THROTTLE_MAX 2000

#define STARTUP_THROTTLE_MIN (THROTTLE_MAX * 0.05)
#define STARTUP_THROTTLE_MAX (THROTTLE_MAX * 0.2)

#define BEMF_FILTER_MIN 2
#define BEMF_FILTER_MAX 12